# version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka-dev
    ports:
      - "9092:9092"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Official Apache image requires a Cluster ID for KRaft
      - KAFKA_CLUSTER_ID=6bc8e63a-44c1-4d10-8b40-97500096677a

  consul:
    image: consul:1.15.4
    container_name: consul-server
    restart: always
    ports:
      - "8500:8500"      # UI and API
      - "8600:8600/udp"  # DNS
    command: "agent -dev -client=0.0.0.0 -ui"
    networks:
      - gateway-network

  db:
      image: kartoza/postgis:18-3.6--v2025.11.24 # Adjust versions as needed (Postgres 15, PostGIS 3.3)
      container_name: postgis_db
      restart: always
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASS=secret
        - POSTGRES_DBNAME=geofleet
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  
  # gateway:
  #   build: .
  #   container_name: gateway-service
  #   depends_on:
  #     - consul
  #   environment:
  #     - CONSUL_ADDRESS=consul:8500
  #     - REDIS_HOST=redis-server
  #   networks:
  #     - gateway-network

volumes:
  postgres_data:

networks:
  gateway-network:
    driver: bridge